name: network_checker_plus
description: A Flutter plugin to check network status, type and signal on Android (iOS support coming soon).
version: 0.0.1
homepage: https://github.com/shubhamdevgupta/network_checker_plus
repository: https://github.com/shubhamdevgupta/network_checker_plus
issue_tracker: https://github.com/shubhamdevgupta/network_checker_plus/issues
maintainer: hutesjk@gmail.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  http: ^1.2.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.network_checker_plus
        pluginClass: NetworkCheckerPlusPlugin
