name: network_checker_plus
description: A Flutter plugin to check network connectivity, type, and more.
version: 1.0.3
homepage: https://github.com/shubhamdevgupta/network_checker_plus
repository: https://github.com/shubhamdevgupta/network_checker_plus
issue_tracker: https://github.com/shubhamdevgupta/network_checker_plus/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.network_checker_plus
        pluginClass: NetworkCheckerPlusPlugin
